// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwNVX64IIOwW9En-B-wwcoDnaTfexeBKw',
    appId: '1:942370941062:web:5a559a9b3d40cdabfac907',
    messagingSenderId: '942370941062',
    projectId: 'ras-chat-449ab',
    authDomain: 'ras-chat-449ab.firebaseapp.com',
    storageBucket: 'ras-chat-449ab.appspot.com',
    measurementId: 'G-3XGY7QKQFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0gCz0a_pLvQptO73U-H2XQ8NoPB5e8E',
    appId: '1:942370941062:android:c2a208808c967585fac907',
    messagingSenderId: '942370941062',
    projectId: 'ras-chat-449ab',
    storageBucket: 'ras-chat-449ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC76mg66eKCbSS4mPW6g_9seLOQywCgHpE',
    appId: '1:942370941062:ios:7b07341390790ec8fac907',
    messagingSenderId: '942370941062',
    projectId: 'ras-chat-449ab',
    storageBucket: 'ras-chat-449ab.appspot.com',
    iosClientId: '942370941062-0a535d67cqs8bmp5shjof44fe2t77vu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC76mg66eKCbSS4mPW6g_9seLOQywCgHpE',
    appId: '1:942370941062:ios:7b07341390790ec8fac907',
    messagingSenderId: '942370941062',
    projectId: 'ras-chat-449ab',
    storageBucket: 'ras-chat-449ab.appspot.com',
    iosClientId: '942370941062-0a535d67cqs8bmp5shjof44fe2t77vu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasChat',
  );
}
